version: '3'

services:

  mongo:
    container_name: coding-challenge-mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoroot
      MONGO_INITDB_ROOT_PASSWORD: mongoroot

  app:
    container_name: coding-challenge-app
    restart: always
    ports:
      - 8181:3000
    build:
      context: .
      dockerfile: app.Dockerfile
    environment:
      - MONGO_HOST=mongo  
    depends_on: 
      - mongo  